//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatesAndCapitalsQuiz_DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class State
    {
        [DisplayName("State Id")]
        public int StateId { get; set; }
        [DisplayName("State")]
        public string State1 { get; set; }
        public string Capital { get; set; }
    }
}
