//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatesAndCapitalsQuiz_DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TestResult
    {
        [DisplayName("Test Result Id")]
        public int TestResultId { get; set; }
        [DisplayName("User Id")]
        public Nullable<int> UserId { get; set; }
        [DisplayName("Test Date")]
        public Nullable<System.DateTime> TestDateTime { get; set; }
        [DisplayName("Total Questions")]
        public Nullable<int> TotalQuestions { get; set; }
        [DisplayName("Result")]
        public Nullable<int> NumberCorrect { get; set; }
    
        public virtual User User { get; set; }
    }
}
