//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatesAndCapitalsQuiz_DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class User_Profile
    {
        [DisplayName("Profile Id")]
        public int ProfileId { get; set; }
        [DisplayName("User Id")]
        public Nullable<int> UserId { get; set; }
        [DisplayName("Admin")]
        public Nullable<bool> admin { get; set; }
    }
}
